import { defineStore } from 'pinia';
import { ref, watch } from 'vue';

export type Language = 'en' | 'km';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Nav / Sidebar ──
    dashboard: 'Dashboard',
    users: 'Users',
    classes: 'Classes',
    subjects: 'Subjects',
    students: 'Students',
    gradebook: 'Gradebook',
    reports: 'Reports',
    appTitle: 'Student Score Management System',
    exit: 'Exit',
    nightMode: 'Night Mode',
    dayMode: 'Day Mode',
    language: 'Language',

    // ── Common UI ──
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    close: 'Close',
    search: 'Search',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    show: 'Show',
    template: 'Template',
    import: 'Import',
    noData: 'No data available.',
    showing: 'Showing',
    to: 'to',
    of: 'of',
    selected: 'selected',
    setActive: 'Set Active',
    setInactive: 'Set Inactive',
    deleteSelected: 'Delete Selected',
    moreActions: 'More actions',
    viewProfile: 'View Profile',
    viewDetails: 'View Details',

    // ── Dashboard ──
    dashboardLoading: 'Loading dashboard analytics...',
    welcomeAdmin: 'Welcome, Administrator!',
    welcomeTeacher: 'Welcome, Teacher / Trainer!',
    welcomeDesc: 'Replace manual grading with our accurate digital score manager. Access student rosters, calculate final grades, and print transcripts.',
    showWelcomeBanner: 'Show welcome banner',
    totalStudents: 'Total Students',
    totalClasses: 'Total Classes',
    totalSubjects: 'Total Subjects',
    passingRate: 'Passing Rate',
    classPerformance: 'Class Performance Averages',
    topPerformers: 'Top Academic Performers',
    noScoresYet: 'No scores entered yet. Go to Gradebook to submit grades.',

    // ── Users ──
    usersLoading: 'Loading system users...',
    userManagement: 'User Management (Admins & Teachers)',
    createUser: 'Create User',
    editUser: 'Edit User',
    saveUser: 'Save User',
    deleteUser: 'Delete this user?',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    systemRole: 'System Role',
    password: 'Password',
    newPassword: 'New Password (Optional)',
    profileImage: 'Profile Image (Avatar)',
    teacher: 'Teacher',
    administrator: 'Administrator',
    userDetailProfile: 'User Detailed Profile',
    closeProfile: 'Close Profile',
    colId: 'ID',
    colName: 'Name',
    colNameKh: 'Name (KH)',
    colEmail: 'Email',
    colRole: 'Role',
    colStatus: 'Status',
    colActions: 'Actions',

    // ── Classes ──
    classesLoading: 'Loading classes...',
    classManagement: 'Class Management',
    createClass: 'Create Class',
    editClass: 'Edit Class',
    saveClass: 'Save Class',
    className: 'Class Name',
    assignedTeacher: 'Assigned Teacher',
    noTeacher: '— No Teacher Assigned —',
    manageSubjects: 'Manage Subjects',
    classSubjects: 'Class Subjects',
    colClass: 'Class',
    colTeacher: 'Teacher',
    colStudents: 'Students',
    colSubjects: 'Subjects',
    totalClassesLabel: 'Total Classes',
    activeClassesLabel: 'Active Classes',
    inactiveClassesLabel: 'Inactive Classes',
    downloadTemplate: 'Download CSV template',
    importData: 'Import',
    addClass: 'Add Class',
    assignSubjects: 'Assign Subjects',
    noSubjectsAssigned: 'No subjects assigned',
    searchClassPlaceholder: 'Search class name...',
    classRosterLabel: 'School Roster & Classes',
    classRosterSubtitle: 'Manage class availability, advisors, and assignments in one place.',

    // ── Subjects ──
    subjectsLoading: 'Loading subjects...',
    subjectManagement: 'Subject Management',
    createSubject: 'Create Subject',
    editSubject: 'Edit Subject',
    saveSubject: 'Save Subject',
    subjectName: 'Subject Name',
    scoreWeights: 'Score Weights',
    assignToClass: 'Assign to Class',
    colSubject: 'Subject',
    colCode: 'Code',
    colClasses: 'Classes',
    colWeights: 'Weights',
    totalSubjectsLabel: 'Total Subjects',
    unassignedSubjectsLabel: 'Unassigned Subjects',
    teachingTutorsLabel: 'Teaching Tutors',
    curriculumSubjectsTitle: 'Curriculum Subjects',
    searchSubjectPlaceholder: 'Search subject...',
    noTeacherAssigned: 'No teacher',
    scoreWeightsLabel: 'Weights',
    assignSubjectButton: 'Assign to Class',
    assignSubjectToClassesTitle: 'Assign Subject to Classes',
    saveAssignments: 'Save Assignments',
    addComponent: 'Add Component',
    selectAllVisibleSubjects: 'Select all visible subjects',
    noSubjectsMatchSearch: 'No subjects match your search.',
    noStudentsMatchSearch: 'No students match your query.',
    notAssignedYet: 'Not assigned yet',
    showLess: 'Show less',

    // ── Students ──
    studentsLoading: 'Loading students...',
    studentManagement: 'Student Management',
    createStudent: 'Create Student',
    editStudent: 'Edit Student',
    saveStudent: 'Save Student',
    studentName: 'Student Name',
    studentNameKh: 'Student Name (KH)',
    classAssignment: 'Class',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    photo: 'Photo',
    filterByClass: 'Filter by Class',
    allClasses: 'All Classes',
    colStudent: 'Student',
    colGender: 'Gender',
    studentRegistryTitle: 'Students Registry',
    searchStudentPlaceholder: 'Search student name...',
    noClassAssigned: 'N/A',

    // ── Gradebook / Scores ──
    scoresTitle: 'Gradebook — Enter Scores',
    selectClass: 'Select Class',
    selectSubject: 'Select Subject',
    chooseClass: '— Choose a class —',
    chooseSubject: '— Choose a subject —',
    selectSubjectPlaceholder: '— Choose Subject —',
    noSubjectsInClass: 'No subjects assigned to this class.',
    saveScores: 'Save Scores',
    saving: 'Saving...',
    scoresSaved: 'Scores saved successfully!',
    colScore: 'Score',
    colTotal: 'Total',
    colGrade: 'Grade',
    colPassed: 'Passed',
    yes: 'Yes',
    no: 'No',
    gradebookSheetTitle: 'Gradebook Sheet',
    gradebookIntro: 'Update grades below. Scores automatically calculate the totals.',
    gradebookEmptyTitle: 'Select Class & Subject',
    gradebookEmptyText: 'Choose a class and a subject from the filters above to open the Direct Grading sheet.',
    noStudentsInClass: 'No students registered in this class.',
    addStudentsHint: 'Add students under the Students tab to view the grading sheet.',
    totalScoreLabel: 'Total (100%)',
    saveGrades: 'Save Grades',
    fetchingGradebook: 'Fetching class gradebook sheet...',

    // ── Reports ──
    reportsTitle: 'Reports & Transcripts',
    generateReport: 'Generate Report',
    printReport: 'Print Report',
    exportCsv: 'Export CSV',
    studentReport: 'Student Report',
    classReport: 'Class Report',
    classRankingsTab: 'Class Rankings',
    studentTranscriptsTab: 'Student Transcripts',
    selectClassPlaceholder: '— Choose Class —',
    selectStudentPlaceholder: '— Choose Student —',
    classRosterMetric: 'Class Roster',
    classAverageMetric: 'Class Average',
    passedMetric: 'Passed (>= 50%)',
    failedMetric: 'Failed (< 50%)',
    classRankingsTitle: 'Class Student Rankings',
    classRankingsSubtitle: 'Ranked by overall average score across graded subjects.',
    printRankings: 'Print Rankings',
    rankHeader: 'Rank',
    studentNameHeader: 'Student Name',
    genderHeader: 'Gender',
    subjectsGradedHeader: 'Subjects Graded',
    averageScoreHeader: 'Average Score',
    overallGradeHeader: 'Overall Grade',
    statusHeader: 'Status',
    selectClassToBeginTitle: 'Select a class to begin',
    selectClassToBeginText: 'Choose a class from the list to compile ranking reports and metrics.',
    studentTranscriptTitle: 'STUDENT ACADEMIC TRANSCRIPT',
    printTranscript: 'Print Transcript',
    idNumberLabel: 'ID Number',
    assignedClassLabel: 'Assigned Class',
    classAdvisorLabel: 'Class Advisor',
    subjectHeader: 'Subject',
    scoringBreakdownHeader: 'Scoring Component Breakdown',
    totalScoreHeader: 'Total Score',
    gradeHeader: 'Grade',
    averageScoreLabel: 'Average Score',
    overallGradeLabel: 'Overall Grade',
    classRankLabel: 'Class Rank',
    academicStatusLabel: 'Academic Status',
    academicSupervisorLabel: 'Academic Supervisor',
    signatureAdvisorLabel: 'Class Advisor',
    selectClassAndStudentTitle: 'Select a class & student',
    selectClassAndStudentText: 'Choose a class and select a student to load their complete academic transcript card.',
    noStudentsGraded: 'No subject scores graded yet.',
    noComponentDetails: 'No component details recorded',
  },

  km: {
    // ── Nav / Sidebar ──
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    users: 'អ្នកប្រើប្រាស់',
    classes: 'ថ្នាក់',
    subjects: 'មុខវិជ្ជា',
    students: 'សិស្ស',
    gradebook: 'សៀវភៅពិន្ទុ',
    reports: 'របាយការណ៍',
    appTitle: 'ប្រព័ន្ធគ្រប់គ្រងពិន្ទុសិស្ស',
    exit: 'ចាកចេញ',
    nightMode: 'របៀបយប់',
    dayMode: 'របៀបថ្ងៃ',
    language: 'ភាសា',

    // ── Common UI ──
    loading: 'កំពុងផ្ទុក...',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    edit: 'កែប្រែ',
    delete: 'លុប',
    create: 'បង្កើត',
    close: 'បិទ',
    search: 'ស្វែងរក',
    actions: 'សកម្មភាព',
    status: 'ស្ថានភាព',
    active: 'សកម្ម',
    inactive: 'អសកម្ម',
    show: 'បង្ហាញ',
    template: 'គំរូ',
    import: 'នាំចូល',
    noData: 'មិនមានទិន្នន័យ។',
    showing: 'បង្ហាញ',
    to: 'ដល់',
    of: 'នៃ',
    selected: 'បានជ្រើស',
    setActive: 'កំណត់ថាសកម្ម',
    setInactive: 'កំណត់ថាអសកម្ម',
    deleteSelected: 'លុបដែលបានជ្រើស',
    moreActions: 'សកម្មភាពបន្ថែម',
    viewProfile: 'មើលប្រវត្តិរូប',
    viewDetails: 'មើលព័ត៌មានលម្អិត',

    // ── Dashboard ──
    dashboardLoading: 'កំពុងផ្ទុកព័ត៌មានសង្ខេប...',
    welcomeAdmin: 'សូមស្វាគមន៍ អ្នកគ្រប់គ្រង!',
    welcomeTeacher: 'សូមស្វាគមន៍ គ្រូបង្រៀន!',
    welcomeDesc: 'ជំនួសការគណនាពិន្ទុដោយដៃ ដោយប្រព័ន្ធឌីជីថលដ៏ត្រឹមត្រូវ។ ចូលប្រើបញ្ជីឈ្មោះសិស្ស គណនាពិន្ទុចុងក្រោយ និងបោះពុម្ពវិញ្ញាបនបត្រ។',
    showWelcomeBanner: 'បង្ហាញបដាស្វាគមន៍',
    totalStudents: 'សិស្សទាំងអស់',
    totalClasses: 'ថ្នាក់ទាំងអស់',
    totalSubjects: 'មុខវិជ្ជាទាំងអស់',
    passingRate: 'អត្រាជាប់',
    classPerformance: 'ប្រតិបត្តិការមធ្យមតាមថ្នាក់',
    topPerformers: 'សិស្សពូកែបំផុត',
    noScoresYet: 'មិនទាន់មានពិន្ទុ។ ចូលទៅ សៀវភៅពិន្ទុ ដើម្បីបញ្ចូលពិន្ទុ។',

    // ── Users ──
    usersLoading: 'កំពុងផ្ទុកបញ្ជីអ្នកប្រើប្រាស់...',
    userManagement: 'គ្រប់គ្រងអ្នកប្រើប្រាស់ (អ្នកគ្រប់គ្រង និងគ្រូ)',
    createUser: 'បង្កើតអ្នកប្រើប្រាស់',
    editUser: 'កែប្រែអ្នកប្រើប្រាស់',
    saveUser: 'រក្សាទុកអ្នកប្រើប្រាស់',
    deleteUser: 'លុបអ្នកប្រើប្រាស់នេះ?',
    fullName: 'ឈ្មោះពេញ',
    emailAddress: 'អាសយដ្ឋានអ៊ីមែល',
    systemRole: 'តួនាទីប្រព័ន្ធ',
    password: 'ពាក្យសម្ងាត់',
    newPassword: 'ពាក្យសម្ងាត់ថ្មី (ស្រេចចិត្ត)',
    profileImage: 'រូបភាពប្រវត្តិរូប',
    teacher: 'គ្រូបង្រៀន',
    administrator: 'អ្នកគ្រប់គ្រង',
    userDetailProfile: 'ព័ត៌មានលម្អិតអ្នកប្រើប្រាស់',
    closeProfile: 'បិទប្រវត្តិរូប',
    colId: 'លេខ',
    colName: 'ឈ្មោះ',
    colNameKh: 'ឈ្មោះខ្មែរ',
    colEmail: 'អ៊ីមែល',
    colRole: 'តួនាទី',
    colStatus: 'ស្ថានភាព',
    colActions: 'សកម្មភាព',

    // ── Classes ──
    classesLoading: 'កំពុងផ្ទុកថ្នាក់...',
    classManagement: 'គ្រប់គ្រងថ្នាក់',
    createClass: 'បង្កើតថ្នាក់',
    editClass: 'កែប្រែថ្នាក់',
    saveClass: 'រក្សាទុកថ្នាក់',
    className: 'ឈ្មោះថ្នាក់',
    assignedTeacher: 'គ្រូដែលបានចាត់តាំង',
    noTeacher: '— មិនទាន់មានគ្រូ —',
    manageSubjects: 'គ្រប់គ្រងមុខវិជ្ជា',
    classSubjects: 'មុខវិជ្ជារបស់ថ្នាក់',
    colClass: 'ថ្នាក់',
    colTeacher: 'គ្រូ',
    colStudents: 'សិស្ស',
    colSubjects: 'មុខវិជ្ជា',
    totalClassesLabel: 'ថ្នាក់ទាំងអស់',
    activeClassesLabel: 'ថ្នាក់សកម្ម',
    inactiveClassesLabel: 'ថ្នាក់អសកម្ម',
    downloadTemplate: 'ទាញយកគំរូ CSV',
    importData: 'នាំចូល',
    addClass: 'បន្ថែមថ្នាក់',
    assignSubjects: 'ចាត់មុខវិជ្ជា',
    noSubjectsAssigned: 'មិនមានមុខវិជ្ជាដែលបានចាត់',
    searchClassPlaceholder: 'ស្វែងរកឈ្មោះថ្នាក់...',
    classRosterLabel: 'បញ្ជីថ្នាក់ និងសិស្ស',
    classRosterSubtitle: 'គ្រប់គ្រងភាពមានសល់នៃថ្នាក់ គ្រូបញ្ជូន និងការចាត់តាំងនៅក្នុងទីតាំងតែមួយ។',

    // ── Subjects ──
    subjectsLoading: 'កំពុងផ្ទុកមុខវិជ្ជា...',
    subjectManagement: 'គ្រប់គ្រងមុខវិជ្ជា',
    createSubject: 'បង្កើតមុខវិជ្ជា',
    editSubject: 'កែប្រែមុខវិជ្ជា',
    saveSubject: 'រក្សាទុកមុខវិជ្ជា',
    subjectName: 'ឈ្មោះមុខវិជ្ជា',
    scoreWeights: 'ទម្ងន់ពិន្ទុ',
    assignToClass: 'ចាត់ថ្នាក់',
    colSubject: 'មុខវិជ្ជា',
    colCode: 'លេខកូដ',
    colClasses: 'ថ្នាក់',
    colWeights: 'ទម្ងន់',
    totalSubjectsLabel: 'មុខវិជ្ជាទាំងអស់',
    unassignedSubjectsLabel: 'មុខវិជ្ជាដែលមិនទាន់ចាត់',
    teachingTutorsLabel: 'គ្រូបង្រៀន',
    curriculumSubjectsTitle: 'មុខវិជ្ជាប្រចាំថ្នាក់',
    searchSubjectPlaceholder: 'ស្វែងរកមុខវិជ្ជា...',
    noTeacherAssigned: 'មិនមានគ្រូ',
    scoreWeightsLabel: 'ទម្ងន់',
    assignSubjectButton: 'ចាត់ទៅថ្នាក់',
    assignSubjectToClassesTitle: 'ចាត់មុខវិជ្ជាទៅថ្នាក់',
    saveAssignments: 'រក្សាទុកការចាត់',
    addComponent: 'បន្ថែមសមាសធាតុ',
    selectAllVisibleSubjects: 'ជ្រើសរើសមុខវិជ្ជាទាំងអស់ដែលមើលឃើញ',
    noSubjectsMatchSearch: 'មិនមានមុខវិជ្ជាដែលស្របនឹងការស្វែងរកទេ។',
    noStudentsMatchSearch: 'មិនមានសិស្សដែលស្របនឹងសំណួរទេ។',
    notAssignedYet: 'មិនទាន់បានចាត់',
    showLess: 'បង្ហាញតិចลง',

    // ── Students ──
    studentsLoading: 'កំពុងផ្ទុកបញ្ជីសិស្ស...',
    studentManagement: 'គ្រប់គ្រងសិស្ស',
    createStudent: 'បង្កើតសិស្ស',
    editStudent: 'កែប្រែសិស្ស',
    saveStudent: 'រក្សាទុកសិស្ស',
    studentName: 'ឈ្មោះសិស្ស',
    studentNameKh: 'ឈ្មោះសិស្សខ្មែរ',
    classAssignment: 'ថ្នាក់',
    gender: 'ភេទ',
    male: 'ប្រុស',
    female: 'ស្រី',
    photo: 'រូបថត',
    filterByClass: 'ត្រង​តាម​ថ្នាក់',
    allClasses: 'ថ្នាក់ទាំងអស់',
    colStudent: 'សិស្ស',
    colGender: 'ភេទ',
    studentRegistryTitle: 'បញ្ជីសិស្ស',
    searchStudentPlaceholder: 'ស្វែងរកឈ្មោះសិស្ស...',
    noClassAssigned: 'មិនមាន',

    // ── Gradebook / Scores ──
    scoresTitle: 'សៀវភៅពិន្ទុ — បញ្ចូលពិន្ទុ',
    selectClass: 'ជ្រើសរើសថ្នាក់',
    selectSubject: 'ជ្រើសរើសមុខវិជ្ជា',
    chooseClass: '— ជ្រើសរើសថ្នាក់ —',
    chooseSubject: '— ជ្រើសរើសមុខវិជ្ជា —',
    selectSubjectPlaceholder: '— ជ្រើសរើសមុខវិជ្ជា —',
    noSubjectsInClass: 'មិនមានមុខវិជ្ជាសម្រាប់ថ្នាក់នេះទេ។',
    saveScores: 'រក្សាទុកពិន្ទុ',
    saving: 'កំពុងរក្សាទុក...',
    scoresSaved: 'ពិន្ទុត្រូវបានរក្សាទុក!',
    colScore: 'ពិន្ទុ',
    colTotal: 'សរុប',
    colGrade: 'ថ្នាក់ទទួល',
    colPassed: 'ជាប់',
    yes: 'បាទ/ចាស',
    no: 'ទេ',
    gradebookSheetTitle: 'សន្លឹកសៀវភៅពិន្ទុ',
    gradebookIntro: 'ធ្វើបច្ចុប្បន្នភាពពិន្ទុខាងក្រោម។ ពិន្ទុត្រូវបានគណនាដោយស្វ័យប្រវត្តិ។',
    gradebookEmptyTitle: 'ជ្រើសរើសថ្នាក់ និងមុខវិជ្ជា',
    gradebookEmptyText: 'ជ្រើសរើសថ្នាក់ និងមុខវិជ្ជាដើម្បីបើកសន្លឹកពិន្ទុដោយផ្ទាល់។',
    noStudentsInClass: 'មិនមានសិស្សដែលបានចុះឈ្មោះនៅក្នុងថ្នាក់នេះទេ។',
    addStudentsHint: 'បន្ថែមសិស្សនៅក្នុងផ្ទាំងសិស្ស ដើម្បីមើលសន្លឹកពិន្ទុ។',
    totalScoreLabel: 'សរុប (100%)',
    saveGrades: 'រក្សាទុកពិន្ទុ',
    fetchingGradebook: 'កំពុងទាញយកសន្លឹកពិន្ទុ...',

    // ── Reports ──
    reportsTitle: 'របាយការណ៍ និងវិញ្ញាបនបត្រ',
    generateReport: 'បង្កើតរបាយការណ៍',
    printReport: 'បោះពុម្ពរបាយការណ៍',
    exportCsv: 'នាំចេញ CSV',
    studentReport: 'របាយការណ៍សិស្ស',
    classReport: 'របាយការណ៍ថ្នាក់',
    classRankingsTab: 'ចំណាត់ថ្នាក់ថ្នាក់',
    studentTranscriptsTab: 'វិញ្ញាបនបត្រសិស្ស',
    selectClassPlaceholder: '— ជ្រើសរើសថ្នាក់ —',
    selectStudentPlaceholder: '— ជ្រើសរើសសិស្ស —',
    classRosterMetric: 'បញ្ជីសិស្សថ្នាក់',
    classAverageMetric: 'មធ្យមភាគថ្នាក់',
    passedMetric: 'ជាប់ (>= 50%)',
    failedMetric: 'មិនជាប់ (< 50%)',
    classRankingsTitle: 'ចំណាត់ថ្នាក់សិស្ស',
    classRankingsSubtitle: 'តាមការគណនាមធ្យមភាគសរុបតាមមុខវិជ្ជាដែលបានពិន្ទុ។',
    printRankings: 'បោះពុម្ពចំណាត់ថ្នាក់',
    rankHeader: 'อันดับ',
    studentNameHeader: 'ឈ្មោះសិស្ស',
    genderHeader: 'ភេទ',
    subjectsGradedHeader: 'មុខវិជ្ជាដែលបានពិន្ទុ',
    averageScoreHeader: 'ពិន្ទុមធ្យម',
    overallGradeHeader: 'ថ្នាក់សរុប',
    statusHeader: 'ស្ថានភាព',
    selectClassToBeginTitle: 'ជ្រើសរើសថ្នាក់ដើម្បីចាប់ផ្តើម',
    selectClassToBeginText: 'ជ្រើសរើសថ្នាក់ពីបញ្ជីដើម្បីបង្កើតរបាយការណ៍ចំណាត់ថ្នាក់ និងទិន្នន័យសង្ខេប។',
    studentTranscriptTitle: 'វិញ្ញាបនបត្រសិក្សាសិស្ស',
    printTranscript: 'បោះពុម្ពវិញ្ញាបនបត្រ',
    idNumberLabel: 'លេខសម្គាល់',
    assignedClassLabel: 'ថ្នាក់ដែលបានចាត់',
    classAdvisorLabel: 'គ្រូបញ្ជូន',
    subjectHeader: 'មុខវិជ្ជា',
    scoringBreakdownHeader: 'ការចែកពិន្ទុ',
    totalScoreHeader: 'ពិន្ទុសរុប',
    gradeHeader: 'ថ្នាក់',
    averageScoreLabel: 'ពិន្ទុមធ្យម',
    overallGradeLabel: 'ថ្នាក់សរុប',
    classRankLabel: 'ចំណាត់ថ្នាក់ក្នុងថ្នាក់',
    academicStatusLabel: 'ស្ថានភាពការសិក្សា',
    academicSupervisorLabel: 'អ្នកត្រួតពិនិត្យសិក្សា',
    signatureAdvisorLabel: 'គ្រូបញ្ជូន',
    selectClassAndStudentTitle: 'ជ្រើសរើសថ្នាក់ និងសិស្ស',
    selectClassAndStudentText: 'ជ្រើសរើសថ្នាក់ និងសិស្សដើម្បីទាញយកវិញ្ញាបនបត្រសិក្សាសិស្ស។',
    noStudentsGraded: 'មិនទាន់មានពិន្ទុមុខវិជ្ជាដែលបានបញ្ចូលទេ។',
    noComponentDetails: 'មិនមានព័ត៌មានលម្អិតអំពីសមាសធាតុពិន្ទុ',
  },
};

export const useUiStore = defineStore('ui', () => {
  const isDarkMode = ref<boolean>(
    localStorage.getItem('darkMode') === 'true',
  );

  const language = ref<Language>(
    (localStorage.getItem('language') as Language) || 'en',
  );

  function t(key: string): string {
    return translations[language.value][key] ?? translations['en'][key] ?? key;
  }

  function toggleDarkMode() {
    isDarkMode.value = !isDarkMode.value;
  }

  function setLanguage(lang: Language) {
    language.value = lang;
  }

  watch(isDarkMode, (val) => {
    localStorage.setItem('darkMode', String(val));
    if (val) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, { immediate: true });

  watch(language, (val) => {
    localStorage.setItem('language', val);
    document.documentElement.lang = val;
  }, { immediate: true });

  return { isDarkMode, language, toggleDarkMode, setLanguage, t };
});
